### PR TITLE
Added slice function

### PR DESCRIPTION
**Pull request by chronoDave**
- slice array from s to e (inclusive)

### CODE REVIEW

**Comment by mindfilleter** [comment]
Not my PR, but it looks like this has been open for a long time. Bumping the thread.

**Comment by sparr** [comment]
There's a performance and token tradeoff here for iterating over all the keys instead of just iterating from s to e. Can you explain the use cases where your chosen implementation is better?

**Comment by mindfilleter** [comment]
I agree with your analysis @sparr . Personally, I'd give the author a few days to respond and then reject the PR if they don't. I would not expect a response from the original author as the request came over 2 years ago.

**Comment by chronoDave** [comment]
I can't remember what my intentions were with this piece of code given it's been 3 years since I wrote it. I'll close this PR.

**Pull request closed without merging**
